Milestone 5: Events
cliftondavies/Math-Magicians pull request #4
Opened 2021-02-11 19:49 UTC by cliftondavies

### Completed:
- [x] Gitflow
- [x] ESLint
- [x] Stylelint
- [x] App component
- [x] ButtonPanel
- [x] Button

2021-02-11 21:15 UTC, Forison requested changes
## Status::Change Required ❌

# Hi @cliftondavies 

#### You have done a good job on this one so far, you code is clean and the click handler has been well implemented, however there is one thing we have to do to get the project approved🤗.

* [ ] Kindly check my comment below👇
* [ ] The calculator is not functional, kindly make sure we can perform simple computation based on the requirement.

#### That is it, kindly make the changes and submit a re-review🤗

#### Happy coding👨‍💻

Addo Forison

2021-02-11 21:15 UTC, Forison commented on src/components/App.js
> +  handleClick(buttonName) {
**[OPTIONAL]**
* [ ] you can declare the method with arrow function to avoid binding it, each time you create.

2021-02-11 21:15 UTC, Forison commented on src/components/App.js
> +        <Display result={total} />
* [ ] it passes the total or next value from state to Display 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/passToatalToDisplay.png))
Currently you are only passing total, it should be `total` or `next`

2021-02-12 01:49 UTC, cliftondavies commented
:wave: @Forison. Thanks for the review. :+1: 

I have applied all required changes; the calculator is now fully functional.

Thanks for the optional suggestion to use an arrow function for **handleClick** in **App.js**. However, I have kept with my initial implementation as the [React Docs on Handling Events](https://reactjs.org/docs/handling-events.html) recommends binding in the constructor, or using class fields, to avoid performance issues with using arrow functions.

I remain to be convinced :smiley:

Happy coding!

2021-02-12 02:18 UTC, bellom approved these changes
## Hi @cliftondavies  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-02-12 12:59 UTC, cliftondavies commented
Thanks, @bellom. 👍

2021-02-12 12:59 UTC, merged